name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag flask:latest
        docker image ls
      
    - name: test docker image
      run: |
        docker run -d --rm flask:latest --name flask
        docker ps
        docker stop flask
